AUTHORS.rst, CHANGES.rst, INSTALL.rst, RELEASE-NOTES.rst, examples/app.py, invenio_rest/__init__.py, invenio_rest/ext.py, invenio_rest/templates/invenio_rest/base.html, invenio_rest/templates/invenio_rest/index.html, invenio_rest/version.py, invenio_rest/views.py, requirements-devel.txt, setup.py, tests/test_invenio_rest.py
* Adds basic error handling and JSON response for common HTTP errors.
* Adds Flask-Limiter for rate limiting support.
* Adds Flask-CORS for Cross-Origin Resource Sharing support (not
enabled by default).
=> global: initial implementation

invenio_rest/errors.py, invenio_rest/views.py, tests/test_invenio_rest.py
* Adds ContentNegotiationMethodView which provides an easy way to create
REST API resources.
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> global: add ContentNegotiationMethodView

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
=> release: 1.0.0a3

invenio_rest/views.py, tests/test_invenio_rest.py
* NEW Adds default media type support to ContentNegotiatedMethodView.
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> utils: default media type for content negotiation

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> release: v1.0.0a4

invenio_rest/version.py
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> version: post-release bump

invenio_rest/views.py, tests/test_invenio_rest.py
* Fixes issue with matching desired serializer when wildcard mimetype
(*/*) was used in accept header.
=> views: accept header matching algorithm fix

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py, invenio_rest/views.py, tests/test_invenio_rest.py
=> release: v1.0.0a5

invenio_rest/ext.py, tests/test_invenio_rest.py
* Adds better CORS configuration.
* Fixes package name typo in error message.
=> ext: typo and better CORS configuration

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
=> release: v1.0.0a6

invenio_rest/ext.py
=> ext: deprecation warning fix

invenio_rest/errors.py, invenio_rest/views.py, tests/test_invenio_rest.py
=> views: check last modified

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
=> release: v1.0.0a7

invenio_rest/errors.py, tests/test_errors.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> global: fix typo in InvalidContentType exception

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
=> release: v1.0.0a8

AUTHORS.rst, invenio_rest/errors.py, invenio_rest/views.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
--
addresses https://github.com/inveniosoftware/invenio-communities/pull/45
=> errors: better SameContentException

docs/conf.py, invenio_rest/views.py, tests/test_invenio_rest.py
* Adds support for checking weak ETags. (closes #39)
=> views: addition of weak ETags check

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> release: v1.0.0a9

docs/api.rst, docs/conf.py, invenio_rest/config.py, invenio_rest/errors.py, invenio_rest/ext.py, invenio_rest/views.py
* Improves documentation. (addresses #46) (closes #48)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> docs: configuration and missing arguments

examples/app.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> examples: simple content negotiated view

README.rst, RELEASE-NOTES.rst
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> docs: pythonhosted.org -> readthedocs.io

examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/requirements.txt, tests/test_examples_app.py
* Adds test_example_app.py. (closes #53)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: addition of test_examples_app.py

INSTALL.rst, README.rst, RELEASE-NOTES.rst, docs/requirements.txt
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> docs: move to readthedocs.io

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> release: v1.0.0a10

INSTALL.rst, README.rst, RELEASE-NOTES.rst, examples/app.py, invenio_rest/config.py, tests/test_examples_app.py
=> docs: example application improvements

.editorconfig, examples/app.py, invenio_rest/config.py, invenio_rest/ext.py, requirements-devel.txt, setup.py, tests/test_invenio_rest.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> global: removal of Flask-Limiter

CHANGES.rst, RELEASE-NOTES.rst, invenio_rest/version.py
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>
=> release: version v1.0.0a11

docs/conf.py, tests/test_invenio_rest.py
* close #81
* intersphinx mapping: fix werkzeug url
* test_error_handlers: skip test for error code 412
[ci skip]
=> global: fix build error

docs/conf.py
Closes https://github.com/inveniosoftware/invenio-rest/issues/89
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>
=> docs: point intersphinx to Flask 0.12

invenio_rest/serializer.py, requirements-devel.txt, setup.py, tests/test_serializer.py
*provide BaseSchema with marshmallow 3 and 2 compatibility
=> schemas: handle marshmallow compatibility in BaseSchema class

CHANGES.rst, invenio_rest/version.py
=> release: v1.1.0

invenio_rest/serializer.py, tests/test_serializer.py
* Fixes the case of editing the '.data' property.
=> schemas: improve the handling of marshmallow compatibility

.travis.yml, examples/app-setup.sh, examples/requirements.txt, requirements-devel.txt, setup.py
* clean travis.yml
closes #104
=> global: centralise flask dependency

examples/app.py, invenio_rest/__init__.py, invenio_rest/config.py, invenio_rest/csrf.py, invenio_rest/errors.py, invenio_rest/ext.py, setup.py, tests/conftest.py, tests/test_csrf.py
Signed-off-by: Pamfilos Fokianos <pamfilosf@gmail.com>
=> global: adds CSRF middleware

invenio_rest/csrf.py
=> csrf: fix check when endpoint does not exists

CHANGES.rst, invenio_rest/config.py, invenio_rest/csrf.py, invenio_rest/version.py, run-tests.sh, setup.py, tests/test_csrf.py
=> csrf: fix token being reset on every request

invenio_rest/csrf.py, invenio_rest/version.py
Change the logic for when the CSRF token should be reset
=> Csrf token reset

.github/workflows/tests.yml, CHANGES.rst, invenio_rest/csrf.py, invenio_rest/version.py, setup.py
- csrf: support aware/naive date_signed comparison
- release: v1.2.8
=> fix datetime comparison

.github/workflows/pypi-publish.yml, CHANGES.rst, invenio_rest/__init__.py, setup.cfg
- setup: pin dependencies
- setup: change to reusable workflows
- release: v1.4.1
=> pin dependencies

.github/workflows/pypi-publish.yml, CHANGES.rst, invenio_rest/__init__.py
- fix: no translation
- release: v1.4.2
=> fix publish workflows

invenio_rest/csrf.py, tests/test_csrf.py
:heart: Thank you for your contribution!
Occurences of APP_ALLOWED_HOSTS were changed to TRUSTED_HOSTS.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your …
=> Replace APP_ALLOWED_HOSTS by TRUSTED_HOSTS.
